name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: 'Build ğŸ§±'
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master

      - name: Setup ğŸ‘¨ğŸ»â€ğŸ’»
        uses: ./.github/actions/setup

      - name: Build Application ğŸ§±
        run: pnpm run build
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

  lint:
    name: 'Check ğŸ±'
    needs: build
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master

      - name: Setup ğŸ‘¨ğŸ»â€ğŸ’»
        uses: ./.github/actions/setup

      - name: Check JS files ğŸ±
        run: pnpm run check
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

  test:
    name: 'Test ğŸ§ª'
    needs: build
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master

      - name: Setup ğŸ‘¨ğŸ»â€ğŸ’»
        uses: ./.github/actions/setup

      - name: Unit Tests ğŸ§ª
        run: pnpm run test
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
